apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-volume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dep-volume-pod
  template:
    metadata:
      labels:
        app: dep-volume-pod
    spec:
      containers:
        - name: dep-volume-container
          image: mohitrathor/kube-pod-volume:latest
          imagePullPolicy: Always