apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-volume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dep-volume-pod
  template:
    metadata:
      labels:
        app: dep-volume-pod
    spec:
      containers:
        - name: dep-volume-container
          image: mohitrathor/kube-pod-volume:latest
          imagePullPolicy: Always
          env:
            - name: STORY_DIR
              value: 'story'
          volumeMounts:
              # mountPath: container internal path where data should be written
            - mountPath: /app/story
              name: story-volume
      # volumes are part of pod, so define at same level
      # as containers.
      volumes:
        - name: story-volume
          # Type of volume: below lines means we want default
          # configuration of this volume type
          # emtpyDir: creates a new empty directory whenever
          #           the pod starts and keeps data as long as pod is alive
          # emptyDir: {}

          hostPath:
            # This volume type creates volumes on the host machine.
            # path is the location on host
            # type is telling to check for the directory if not present create one.
            - path: /data
              type: DirectoryOrCreate

          # persistent volume, we add claim detail here:
          # persistentVolumeClaim:
          #   claimName: host-pvc