apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  # name of persistent volume that needs to be claimed.
  # This is claiming by name and called static provisioning
  volumeName: host-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi