apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dep
spec: # specifications for deployment object
  replicas: 2
  selector:
    matchLabels:
      # This deployment now can control the pod
      # with this label
      app: my-dep-pod
  template:
    metadata:
      labels:
        app: my-dep-pod
    spec: # specifications for pod object
      containers:
        - name: my-dep-container
          image: mohitrathor/kube-pod-demo:1
