apiVersion: app/v1
kind: deployment
metadata:
  name: my-dep
spec: # specifications for deployment object
  replicas: 3
  selector:
    matchLabels:
      # This deployment now can control the pod
      # with this label
      app: my-dep-pod
  template:
    metadata:
      labels:
        app: my-dep-pod
    spec: # specifications for pod object
      containers:
        - name: my-dep-container
          image: academind/kube-first-app:2
