apiVersion: v1 # for services, version is v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    # for services, we don't need to provide
    # matchLabel key.
    app: my-dep-pod # Giving pod name for which we are creating the service
  ports:
    - protocol: 'TCP'
      port: 80 # port that will be exposed on machine
      targetPort: 8080 # port that application inside the container is listening
  type: LoadBalancer   
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dep
spec: # specifications for deployment object
  replicas: 2
  selector:
    matchLabels:
      # This deployment now can control the pod
      # with this label
      app: my-dep-pod
  template:
    metadata:
      labels:
        app: my-dep-pod
    spec: # specifications for pod object
      containers:
        - name: my-dep-container
          image: mohitrathor/kube-pod-demo:1
