apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: app-auth
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 80
  # Not accessible to outside the cluster
  type: ClusterIP