apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-users
  template:
    metadata:
      labels:
        app: auth-users
    spec:
      containers:
        - name: app-auth-container
          image: mohitrathor/auth-api:latest
          imagePullPolicy: Always
          