apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-tasks
  template:
    metadata:
      labels:
        app: app-tasks
    spec:
      containers:
        - name: app-tasks-container
          image: mohitrathor/tasks-api:latest
          imagePullPolicy: Always
          env:
            - name: AUTH_ADDRESS
              value: "auth-service.default"
            - name: TASKS_FOLDER
              value: tasks