apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-users
  template:
    metadata:
      labels:
        app: app-users
    spec:
      containers:
        - name: app-users-container
          image: mohitrathor/users-api:latest
          imagePullPolicy: Always
          env:
            - name: AUTH_ADDRESS
              value: localhost
        - name: auth
          image: mohirathor/auto-api:latest
          